var hierarchy =
[
    [ "cimg_library::CImg< T >::_cimg_math_parser", "structcimg__library_1_1_c_img_1_1__cimg__math__parser.html", null ],
    [ "cimg_library::CImg< T >::_functor2d_expr", "structcimg__library_1_1_c_img_1_1__functor2d__expr.html", null ],
    [ "cimg_library::CImg< T >::_functor2d_float", "structcimg__library_1_1_c_img_1_1__functor2d__float.html", null ],
    [ "cimg_library::CImg< T >::_functor2d_int", "structcimg__library_1_1_c_img_1_1__functor2d__int.html", null ],
    [ "cimg_library::CImg< T >::_functor3d_expr", "structcimg__library_1_1_c_img_1_1__functor3d__expr.html", null ],
    [ "cimg_library::CImg< T >::_functor3d_float", "structcimg__library_1_1_c_img_1_1__functor3d__float.html", null ],
    [ "cimg_library::CImg< T >::_functor3d_int", "structcimg__library_1_1_c_img_1_1__functor3d__int.html", null ],
    [ "cimg_library::CImg< T >::_functor4d_int", "structcimg__library_1_1_c_img_1_1__functor4d__int.html", null ],
    [ "cimg_library::CImg< T >::_functor4d_streamline2d_directed", "structcimg__library_1_1_c_img_1_1__functor4d__streamline2d__directed.html", null ],
    [ "cimg_library::CImg< T >::_functor4d_streamline2d_oriented", "structcimg__library_1_1_c_img_1_1__functor4d__streamline2d__oriented.html", null ],
    [ "cimg_library::CImg< T >::_functor4d_streamline3d_directed", "structcimg__library_1_1_c_img_1_1__functor4d__streamline3d__directed.html", null ],
    [ "cimg_library::CImg< T >::_functor4d_streamline3d_oriented", "structcimg__library_1_1_c_img_1_1__functor4d__streamline3d__oriented.html", null ],
    [ "cimg_library::CImg< T >::_functor4d_streamline_expr", "structcimg__library_1_1_c_img_1_1__functor4d__streamline__expr.html", null ],
    [ "cimg_library::CImg< T >::_functor_isoline3d", "structcimg__library_1_1_c_img_1_1__functor__isoline3d.html", null ],
    [ "cimg_library::CImg< T >::_functor_isosurface3d", "structcimg__library_1_1_c_img_1_1__functor__isosurface3d.html", null ],
    [ "camera", "classcamera.html", null ],
    [ "cimg_library::CImg< T >", "structcimg__library_1_1_c_img.html", null ],
    [ "cimg_library::CImg< charT >", "structcimg__library_1_1_c_img.html", null ],
    [ "cimg_library::CImg< doubleT >", "structcimg__library_1_1_c_img.html", null ],
    [ "cimg_library::CImg< floatT >", "structcimg__library_1_1_c_img.html", null ],
    [ "cimg_library::CImg< intT >", "structcimg__library_1_1_c_img.html", null ],
    [ "cimg_library::CImg< uintT >", "structcimg__library_1_1_c_img.html", null ],
    [ "cimg_library::CImg< ulongT >", "structcimg__library_1_1_c_img.html", null ],
    [ "cimg_library::CImgList< T >", "structcimg__library_1_1_c_img_list.html", null ],
    [ "cimg_library::CImgList< charT >", "structcimg__library_1_1_c_img_list.html", null ],
    [ "cimg_library::CImgList< doubleT >", "structcimg__library_1_1_c_img_list.html", null ],
    [ "cimg_library::CImgList< ulongT >", "structcimg__library_1_1_c_img_list.html", null ],
    [ "std::exception", null, [
      [ "cimg_library::CImgAbortException", "structcimg__library_1_1_c_img_abort_exception.html", null ],
      [ "cimg_library::CImgException", "structcimg__library_1_1_c_img_exception.html", [
        [ "cimg_library::CImgArgumentException", "structcimg__library_1_1_c_img_argument_exception.html", null ],
        [ "cimg_library::CImgDisplayException", "structcimg__library_1_1_c_img_display_exception.html", null ],
        [ "cimg_library::CImgIOException", "structcimg__library_1_1_c_img_i_o_exception.html", null ],
        [ "cimg_library::CImgInstanceException", "structcimg__library_1_1_c_img_instance_exception.html", null ],
        [ "cimg_library::CImgWarningException", "structcimg__library_1_1_c_img_warning_exception.html", null ]
      ] ]
    ] ],
    [ "Face", "class_face.html", null ],
    [ "hit_record", "classhit__record.html", null ],
    [ "hittable", "classhittable.html", [
      [ "Triangulo", "class_triangulo.html", null ],
      [ "hittable_list", "classhittable__list.html", null ],
      [ "sphere", "classsphere.html", null ]
    ] ],
    [ "interval", "classinterval.html", null ],
    [ "ivec3", "classivec3.html", null ],
    [ "cimg_library::cimg::last< t1, t2 >", "structcimg__library_1_1cimg_1_1last.html", null ],
    [ "mat2", "classmat2.html", null ],
    [ "mat3", "classmat3.html", null ],
    [ "mat4", "classmat4.html", null ],
    [ "material", "classmaterial.html", [
      [ "dielectric", "classdielectric.html", null ],
      [ "lambertian", "classlambertian.html", null ],
      [ "metal", "classmetal.html", null ]
    ] ],
    [ "cimg_library::cimg::Mutex_static", "structcimg__library_1_1cimg_1_1_mutex__static.html", null ],
    [ "Normais", "class_normais.html", null ],
    [ "Objeto", "class_objeto.html", null ],
    [ "Ray", "class_ray.html", null ],
    [ "cimg_library::cimg::superset< T, t >", "structcimg__library_1_1cimg_1_1superset.html", null ],
    [ "cimg_library::cimg::superset2< t1, t2, t3 >", "structcimg__library_1_1cimg_1_1superset2.html", null ],
    [ "cimg_library::cimg::superset3< t1, t2, t3, t4 >", "structcimg__library_1_1cimg_1_1superset3.html", null ],
    [ "cimg_library::cimg::superset< bool, char >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, double >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, float >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, int >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, short >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, signed char >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01signed_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, unsigned char >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01unsigned_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, unsigned int >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< bool, unsigned short >", "structcimg__library_1_1cimg_1_1superset_3_01bool_00_01unsigned_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, double >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, float >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, int >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, short >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, signed char >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01signed_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, unsigned char >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01unsigned_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, unsigned int >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< char, unsigned short >", "structcimg__library_1_1cimg_1_1superset_3_01char_00_01unsigned_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_int64, double >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__int64_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_int64, float >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__int64_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_uint64, char >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__uint64_00_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_uint64, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__uint64_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_uint64, double >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__uint64_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_uint64, float >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__uint64_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_uint64, int >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__uint64_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_uint64, short >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__uint64_00_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< cimg_uint64, signed char >", "structcimg__library_1_1cimg_1_1superset_3_01cimg__uint64_00_01signed_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< float, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01float_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< float, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01float_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< float, double >", "structcimg__library_1_1cimg_1_1superset_3_01float_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< int, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01int_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< int, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01int_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< int, double >", "structcimg__library_1_1cimg_1_1superset_3_01int_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< int, float >", "structcimg__library_1_1cimg_1_1superset_3_01int_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< int, unsigned int >", "structcimg__library_1_1cimg_1_1superset_3_01int_00_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< short, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01short_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< short, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01short_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< short, double >", "structcimg__library_1_1cimg_1_1superset_3_01short_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< short, float >", "structcimg__library_1_1cimg_1_1superset_3_01short_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< short, int >", "structcimg__library_1_1cimg_1_1superset_3_01short_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< short, unsigned int >", "structcimg__library_1_1cimg_1_1superset_3_01short_00_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< short, unsigned short >", "structcimg__library_1_1cimg_1_1superset_3_01short_00_01unsigned_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, char >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, double >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, float >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, int >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, short >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, unsigned char >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01unsigned_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, unsigned int >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< signed char, unsigned short >", "structcimg__library_1_1cimg_1_1superset_3_01signed_01char_00_01unsigned_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, char >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, double >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, float >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, int >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, short >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, signed char >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01signed_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, unsigned int >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned char, unsigned short >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01char_00_01unsigned_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, char >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, double >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, float >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, int >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, short >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned int, signed char >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01int_00_01signed_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, char >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, cimg_int64 >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, cimg_uint64 >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, double >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01double_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, float >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01float_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, int >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01int_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, short >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01short_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, signed char >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01signed_01char_01_4.html", null ],
    [ "cimg_library::cimg::superset< unsigned short, unsigned int >", "structcimg__library_1_1cimg_1_1superset_3_01unsigned_01short_00_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::type< T >", "structcimg__library_1_1cimg_1_1type.html", null ],
    [ "cimg_library::cimg::type< bool >", "structcimg__library_1_1cimg_1_1type_3_01bool_01_4.html", null ],
    [ "cimg_library::cimg::type< char >", "structcimg__library_1_1cimg_1_1type_3_01char_01_4.html", null ],
    [ "cimg_library::cimg::type< cimg_int64 >", "structcimg__library_1_1cimg_1_1type_3_01cimg__int64_01_4.html", null ],
    [ "cimg_library::cimg::type< cimg_uint64 >", "structcimg__library_1_1cimg_1_1type_3_01cimg__uint64_01_4.html", null ],
    [ "cimg_library::cimg::type< double >", "structcimg__library_1_1cimg_1_1type_3_01double_01_4.html", null ],
    [ "cimg_library::cimg::type< float >", "structcimg__library_1_1cimg_1_1type_3_01float_01_4.html", null ],
    [ "cimg_library::cimg::type< int >", "structcimg__library_1_1cimg_1_1type_3_01int_01_4.html", null ],
    [ "cimg_library::cimg::type< long double >", "structcimg__library_1_1cimg_1_1type_3_01long_01double_01_4.html", null ],
    [ "cimg_library::cimg::type< short >", "structcimg__library_1_1cimg_1_1type_3_01short_01_4.html", null ],
    [ "cimg_library::cimg::type< signed char >", "structcimg__library_1_1cimg_1_1type_3_01signed_01char_01_4.html", null ],
    [ "cimg_library::cimg::type< unsigned char >", "structcimg__library_1_1cimg_1_1type_3_01unsigned_01char_01_4.html", null ],
    [ "cimg_library::cimg::type< unsigned int >", "structcimg__library_1_1cimg_1_1type_3_01unsigned_01int_01_4.html", null ],
    [ "cimg_library::cimg::type< unsigned short >", "structcimg__library_1_1cimg_1_1type_3_01unsigned_01short_01_4.html", null ],
    [ "vec2", "classvec2.html", null ],
    [ "vec3", "classvec3.html", null ],
    [ "vec4", "classvec4.html", null ]
];